const $=id=>document.getElementById(id);let generatedFiles={};let lastMeta={};
const home=$('home'),studio=$('studio'),prompt=$('prompt'),iframe=$('sitePreview'),build=$('buildBtn');
document.querySelectorAll('.examples button').forEach(b=>b.onclick=()=>{prompt.value=b.textContent;prompt.focus()});
$('studioBtn').onclick=()=>openStudio();$('backBtn').onclick=()=>{studio.classList.add('hidden');home.classList.remove('hidden')};
$('refreshBtn').onclick=()=>{iframe.srcdoc=iframe.srcdoc};
document.querySelectorAll('.device').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('.device').forEach(x=>x.classList.remove('active'));b.classList.add('active');iframe.style.maxWidth=i===0?'100%':i===1?'820px':'390px';iframe.style.margin='0 auto'});
function openStudio(){home.classList.add('hidden');studio.classList.remove('hidden')}
function setStep(n){document.querySelectorAll('.step').forEach((x,i)=>x.classList.toggle('active',i===n))}
function activity(name,text,index){$('activityName').textContent=name;$('activityText').textContent=text;document.querySelectorAll('.activity-item').forEach((x,i)=>{x.classList.toggle('current',i===index);x.querySelector('span').textContent=i===index?'◉':'○'})}
function showFiles(files){generatedFiles=files;$('fileList').innerHTML=Object.keys(files).map(k=>'◦ '+k).join('<br>')}
function makePreview(files){let doc=files['index.html']||'';const css=files['styles.css']||'',js=files['script.js']||'';if(!/<style/i.test(doc)&&css)doc=doc.replace('</head>','<style>'+css+'</style></head>');if(js&&!/<script/i.test(doc))doc=doc.replace('</body>','<script>'+js.replace(/<\/script/gi,'<\\/script')+'</script></body>');iframe.srcdoc=doc}
async function generate(){const text=prompt.value.trim();if(!text){prompt.focus();return}build.disabled=true;$('error').classList.add('hidden');openStudio();$('projectTitle').textContent=text.length>65?text.slice(0,65)+'…':text;activity('Thinking','Entendiendo el negocio',0);
try{await new Promise(r=>setTimeout(r,250));activity('Planning','Eligiendo arquitectura',0);const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:text})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Generación falló');lastMeta=data.meta||{};$('designMeta').textContent='Arquetipo: '+(lastMeta.archetype||'—')+' · Dirección: '+(lastMeta.direction||'—')+' · Fuente: '+(data.source||'—');activity('Design','Dirección: '+(lastMeta.direction||'visual'),1);await new Promise(r=>setTimeout(r,300));activity('Building','Construyendo composición '+(lastMeta.archetype||''),2);showFiles(data.files);makePreview(data.files);await new Promise(r=>setTimeout(r,400));activity('QA','Resultado listo para inspección',3)}catch(e){$('error').textContent='Error de generación: '+e.message;$('error').classList.remove('hidden');activity('Error','La generación necesita revisión',3)}finally{build.disabled=false}}
build.onclick=generate;
$('downloadBtn').onclick=async()=>{if(!Object.keys(generatedFiles).length){alert('Genera primero una web.');return}if(typeof JSZip==='undefined'){alert('No se pudo cargar el exportador ZIP.');return}const z=new JSZip();for(const [n,c] of Object.entries(generatedFiles))z.file(n,c);z.file('FORJA-META.json',JSON.stringify(lastMeta,null,2));const blob=await z.generateAsync({type:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='forja-generated-site.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
